global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'searchContainer'
    static_configs:
      - targets: ['search-container:8085']
  - job_name: 'meilisearch'
    static_configs:
      - targets: ["meilisearch:7700"]
    authorization:
      credentials: "masterKey"
  - job_name: 'searchCron'
    static_configs:
      - targets: ["search-cron:8090"]